name: My First Workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        steps:
        - name: Welcome message
          run: echo "My first Github Actions Job"

        - name: Checkout repo
          uses: actions/checkout@v6
        
        - name: List files
          run: ls

        - name: Read file
          run: cat README.md

        - name: Test Multiline cmd
          run: |
            echo "Testing cmd 1"
            ls -al
            echo "Testing cmd 2"
            cat README.md

        - name: Generate ASCII  Artwork
          run: cowsay -f dog "Awwwww Awwwww" > dog.txt
