name: Run Script

on: push

jobs: 
  ascii-job: 
    runs-on: ubuntu-latest
    steps:
      - name: List Repo Files
        run: ls -ltra

      - name: Running a script
        chmod +x ascii-script.sh
        run: ./ascii-script.sh